name: Build

on:
  workflow_dispatch:
    inputs:
      upload_artifacts:
        description: 'Upload artifacts?'
        type: boolean
      show_log:
        description: 'Show build log?'
        type: boolean
  schedule:
    - cron: "0 1 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.PAT }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - name: Build
        run: ./build.sh
        env:
          SHOW_LOG: ${{ inputs.show_log == true }}
          GH_TOKEN: ${{ secrets.PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          EDGEONE_TOKEN: ${{ secrets.EDGEONE_TOKEN }}

      - name: Upload artifacts
        if: ${{ inputs.upload_artifacts == true }}
        uses: actions/upload-artifact@v5
        with:
          name: laravel-docs-dist
          path: .vitepress/dist
